apiVersion: v1
kind: Service
metadata:
  name: sprint3
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    app: sprint3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sprint3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sprint3
  template:
    metadata:
      labels:
        app: sprint3
    spec:
      containers:
        - name: sprint3
          image: sprint3:1.0
